structure(list(url = "https://irmaservices.nps.gov/datastore/v7/rest/DownloadFile/709657", 
    status_code = 200L, headers = structure(list(`cache-control` = "no-cache", 
        pragma = "no-cache", `content-length` = "46196", `content-type` = "application/vnd.openxmlformats-officedocument.wordprocessingml.document", 
        expires = "-1", `last-modified` = "Mon, 07 Oct 2024 23:01:46 GMT", 
        etag = "\"JiKc4h1lBnF604+Ou4BVGvhD33U/E7zZEUMT7UHsAJPgj1NpMizsHbV5UDMy9R4LlmuTUupMNIk3VjKm5+K31w==\"", 
        server = "Microsoft-IIS/10.0", `content-disposition` = "attachment; filename=\"Checklist_for_data_package_review2024_10_07.docx\"; size=46196; modification-date=\"Mon, 07 Oct 2024 23:01:46 GMT\"", 
        `x-aspnet-version` = "4.0.30319", `strict-transport-security` = "max-age=480; includeSubDomains", 
        `frame-ancestors` = "*.nps.gov", `x-frame-options` = "SAMEORIGIN", 
        date = "Mon, 12 May 2025 16:50:43 GMT"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 200L, version = "HTTP/1.1", 
        headers = structure(list(`cache-control` = "no-cache", 
            pragma = "no-cache", `content-length` = "46196", 
            `content-type` = "application/vnd.openxmlformats-officedocument.wordprocessingml.document", 
            expires = "-1", `last-modified` = "Mon, 07 Oct 2024 23:01:46 GMT", 
            etag = "\"JiKc4h1lBnF604+Ou4BVGvhD33U/E7zZEUMT7UHsAJPgj1NpMizsHbV5UDMy9R4LlmuTUupMNIk3VjKm5+K31w==\"", 
            server = "Microsoft-IIS/10.0", `content-disposition` = "attachment; filename=\"Checklist_for_data_package_review2024_10_07.docx\"; size=46196; modification-date=\"Mon, 07 Oct 2024 23:01:46 GMT\"", 
            `x-aspnet-version` = "4.0.30319", `strict-transport-security` = "max-age=480; includeSubDomains", 
            `frame-ancestors` = "*.nps.gov", `x-frame-options` = "SAMEORIGIN", 
            date = "Mon, 12 May 2025 16:50:43 GMT"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = structure(find_mock_file("irmaservices.nps.gov/datastore/v7/rest/DownloadFile/709657.R-FILE"), 
        class = "path"), date = structure(1747068643, class = c("POSIXct", 
    "POSIXt"), tzone = "GMT"), times = c(redirect = 0, namelookup = 2.4e-05, 
    connect = 0, pretransfer = 0.000476, starttransfer = 0.195451, 
    total = 0.197868)), class = "response")
