structure(list(url = "https://irmaservices.nps.gov/datastore/v7/rest/DownloadFile/687284", 
    status_code = 200L, headers = structure(list(`cache-control` = "no-cache", 
        pragma = "no-cache", `content-length` = "69856", `content-type` = "application/octet-stream", 
        expires = "-1", `last-modified` = "Sat, 06 May 2023 04:42:32 GMT", 
        etag = "\"HIcd5rNcHZF5NPKCFGs13MH+IsqpRlM8yoMPUFD3ZdUCVU2SwWJfE5Ticd6bRzoIpJOg79AW3fG77E092Mpu9w==\"", 
        server = "Microsoft-IIS/10.0", `content-disposition` = "attachment; filename=\"CAHA_Fish_Cleaned_PUBLIC.csv\"; size=69856; modification-date=\"Sat, 06 May 2023 04:42:32 GMT\"", 
        `x-aspnet-version` = "4.0.30319", `strict-transport-security` = "max-age=480; includeSubDomains", 
        `frame-ancestors` = "*.nps.gov", `x-frame-options` = "SAMEORIGIN", 
        date = "Tue, 13 May 2025 19:51:02 GMT"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 200L, version = "HTTP/1.1", 
        headers = structure(list(`cache-control` = "no-cache", 
            pragma = "no-cache", `content-length` = "69856", 
            `content-type` = "application/octet-stream", expires = "-1", 
            `last-modified` = "Sat, 06 May 2023 04:42:32 GMT", 
            etag = "\"HIcd5rNcHZF5NPKCFGs13MH+IsqpRlM8yoMPUFD3ZdUCVU2SwWJfE5Ticd6bRzoIpJOg79AW3fG77E092Mpu9w==\"", 
            server = "Microsoft-IIS/10.0", `content-disposition` = "attachment; filename=\"CAHA_Fish_Cleaned_PUBLIC.csv\"; size=69856; modification-date=\"Sat, 06 May 2023 04:42:32 GMT\"", 
            `x-aspnet-version` = "4.0.30319", `strict-transport-security` = "max-age=480; includeSubDomains", 
            `frame-ancestors` = "*.nps.gov", `x-frame-options` = "SAMEORIGIN", 
            date = "Tue, 13 May 2025 19:51:02 GMT"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = structure(find_mock_file("irmaservices.nps.gov/datastore/v7/rest/DownloadFile/687284.R-FILE"), 
        class = "path"), date = structure(1747165862, class = c("POSIXct", 
    "POSIXt"), tzone = "GMT"), times = c(redirect = 0, namelookup = 2.2e-05, 
    connect = 0, pretransfer = 0.000423, starttransfer = 0.352057, 
    total = 0.425047)), class = "response")
