#' Read contents of data package(s) and return a tibble with a tibble for each data file. 
#' 
#' `r lifecycle::badge("experimental")`
#'
#' @description `load_data_packages()` finds all the specified data packages in a /data directory (generated via `get_data_packages()`) and returns a tibble of tibbles where each data package is a tibble and within that each data file is it's own tibble. `load_data_packages()` also utilizes the metadata (only EML is currently supported) to correctly assign attributes to each data column.
#' 
#' @details currently `load_data_packages()` only supports EML metadata and .csv files in a very specific file structure, which is most easily set up using `get_data_packages()`. Archived (.zip) files must be extracted for `load_data_packages()` to work properly. Again, `get_data_packages()` will accomplish this for you. 
#' '
#' @param datastore_reference is a list of 6-7 digit numbers corresponding to the DataStore reference ID of the datapackage(s) to load. Alternatively, you can set `datastore_reference` to "loadAll", which will load all the data packages in your /data folder.
#' @param path is the location of a folder, 'data' (created during `get_data_packages()`) which contains sub-directories where each sub-directory is the DataStore referenceId of the data package. Again, this file structure is all set up using `get_data_packages()`. Defaults to the current working directory (which is the default location for `get_data_packages()`). 
#' @param assing_attributes Logical. Defaults to FALSE. if set to TRUE, the column types in each tibble will be assigned using information from the metadata rather than the default guesses generated by `reader::read_csv()`.
#' @param data_format is a character value indicating the format of the data set(s) within the data package. Currently the only supported option is: *.csv for comma separated value text files. Defaults to "csv".
#' @param metadata_format is a character value indicating the format of the metadata file within the data package. Currently the only supported format is Ecological Metadata (EML) and the parameter defaults to EML.
#' @param simplify logical. Defaults to TRUE. If there is only a single data package loaded, the function will return a simple list of tibbles (where each tibble reflects a data file from within the data package). If set to FALSE, the function will return a list that contains a list of tibbles. This structure mirrors the object structure returned if multiple data packages are simultaneously loaded (a list of data packages with each data package containing a list of tibbles where each tibble corresponds to a data file in the given data package).
#'
#' @return a list of (of lists of) tibbles. 
#'
#' @export
#' 
#' @examples
#' \dontrun{
#' dat <- load_data_packages(2272461,
#'                          data_format = "csv",
#'                          metadata_format = "eml")
#' }
#'
load_data_packages <- function(datastore_reference, 
                             path = here::here(),
                             assign_attributes = FALSE,
                             data_format = "*.csv",
                             metadata_format = "EML",
                             simplify = TRUE){
  #capture original working directory
  orig_wd <- getwd()
  #set directory back to original working directory on exit.
  on.exit(setwd(orig_wd))
  #set wd to path; defaults to wd. 
  setwd(path)
  
  #is user specifies "allData" get all directories from the data folder:
  if (datasore_reference == "allData") {
    datastore_reference <- list.dirs(path = path,
                                     full.names = FALSE,
                                     recursive = FALSE)
  }
  
  ### fix how single data packages are handled later:
  if(length(
    seq_along(
      datastore_reference)) == 1 
    & datastore_reference != "allData" 
    & simplify == TRUE) {
  #return a tibble of data files  
  }
  
  
  for(i in 1:seq_along(datastore_reference)){
    data_package_directory <- paste("data/", datastore_reference[i])
    filenames <- list.files(
      path = data_package_directory,
      pattern = data_format)
    ## Create list of data frame names without the ".csv" part
    names <- gsub(pattern = "\\.csv$", "", filenames)
    
    ### Load all files into tibbles
    datastore_reference[i] <- list()
    for (j in names) {
      filepath <- file.path(data_package_directory, paste(j, ".csv", sep = ""))
      tibble_List[[i]] <- assign(j,
                                 readr::read_csv(filepath,
                                                 show_col_types = FALSE))
    }

    
        
  }
  
  DataPackageFilename <- paste(DataPackageDirectory, "/", holding_id, ".zip", sep = "")

  if (data_format == "csv" & metadata_format == "eml") {
    fileList <- utils::unzip(DataPackageFilename, list = TRUE)
    return(fileList)
  } else if (data_format == "gdb" & metadata_format == "fgdc") {
    # And now working with the file geodatabase
    gdbfile <- list.dirs(
      path = DataPackageDirectory,
      full.names = TRUE,
      recursive = FALSE
    )
    fGDB <- paste0(getwd(), "/", gdbfile)
    datasets <- sf::st_layers(fGDB, do_count = TRUE)
    datasets <- datasets$name

    datasetList <- data.frame(dataset = character(), stringsAsFactors = FALSE)

    for (i in 1:length(datasets)) {
      temp <- sf::st_read(dsn = fGDB, layer = datasets[i], stringsAsFactors = FALSE)

      if (class(temp[1]) == "sf") {
        temp2 <- data.frame(dataset = datasets[i], stringsAsFactors = FALSE)
        datasetList <- rbind.data.frame(datasetList, temp2, stringsAsFactors = FALSE)
      }
    }
    return(datasetList)
  } else {
    print("data/metadata format combination not supported")
  }
}
